### ISSUE TITLE
restriction site file

### ISSUE THREAD

**Issue by hurleyLi** [theaidenlab/juicer#1]
Hi, 
Thanks for sharing the code in this much detail! 

just wondering where can I find the restriction site file

```
$site_file = "/opt/juicer/restriction_sites/hg19_DpnII.txt";
```

Is it generated by HICUP? just wanna know what's the format look like.

Thanks!
Hurley

**Comment by nchernia** [comment]
Hi Hurley,

It's a whitespace-delimited file.  There is no header.  Each line has as
the first field the chromosome, followed by the list of restriction sites,
in increasing order.  The last field is the size of the chromosome.

E.g.:
1 11160 12411 12461 ... 249250621
2 11514 11874 12160 ... 243199373
...

The restriction sites are the location of the motif of the restriction
enzyme in the reference genome.  So in this example, the first location of
GATC in hg19 on chromosome 1 is 11160, then 12411, then 12461, etc.

Best
Neva

**Comment by hurleyLi** [comment]
Got it! Thanks Neva!
