### ISSUE TITLE
how to a convert contact matrix to hic file

### ISSUE THREAD

**Issue by hzlzldr** [theaidenlab/juicer#101]
hi everyone，I'm a new to hic and Juicer,i have encountered some difficulties.We know,we can Extracting data from .hic files with dump,the data is a coordinate list file,then i have some processed with the coordinate list file,which is different with the former.
  I just want to know what can i do from the new coordinate list file to create a new hic file?
  Thanks!

**Comment by nchernia** [comment]
This was answered on the forum
