### ISSUE TITLE
Eigenvector : how to flip the values

### ISSUE THREAD

**Issue by QianzhaoJ** [theaidenlab/juicer#103]
Hi : 
    Seems like the output of `Eigenvector` is oriented randomly for each chromosome , Is there a parameter to flip the values to have a positive correlation with some tracks associated with activity (such as gene density ) for each chromosome  in `Eigenvector` ?
 
Best wishes
Qianzhao

**Comment by nchernia** [comment]
This is now possible within Juicebox (see: https://github.com/aidenlab/Juicebox/issues/737 )

Possibly it should also just happen automatically, in which case this should be an issue in Juicebox, where the Eigenvector code lives.
