### ISSUE TITLE
Error running on PBS cluster

### ISSUE THREAD

**Issue by sisyyuan** [theaidenlab/juicer#105]
command:
 ./juicer/PBS/scripts/juicer.sh -g draft -s HindIII -z draft.fa -y draft_HindIII.txt -p assembly

Error:
socket_connect_unix failed: 15137
qsub: cannot connect to server (null) (errno=15137) could not connect to trqauthd
socket_connect_unix failed: 15137
qsub: cannot connect to server (null) (errno=15137) could not connect to trqauthd
socket_connect_unix failed: 15137
qsub: cannot connect to server (null) (errno=15137) could not connect to trqauthd
socket_connect_unix failed: 15137
qsub: cannot connect to server (null) (errno=15137) could not connect to trqauthd
[qsub: illegal -W dependency value: 'afterok::::']

usage: qsub [-a date_time] [-A account_string] [-b secs]
    [-c [ none | { enabled | periodic | shutdown |
    depth=<int> | dir=<path> | interval=<minutes>}... ]
    [-C directive_prefix] [-d path] [-D path]
    [-e path] [-h] [-I] [-j oe|eo|n] [-k {oe}] [-K <kill delay seconds>]
    [-l resource_list] [-m n|{abe}] [-M user_list] [-N jobname] [-o path]
    [-p priority] [-P proxy_user [-J <jobid]] [-q queue] [-r y|n]
    [-S path] [-t number_to_submit] [-T type]  [-u user_list] [-w] path
    [-W additional_attributes] [-v variable_list] [-V ] [-x] [-X] [-z] [script]

socket_connect_unix failed: 15137
qsub: cannot connect to server (null) (errno=15137) could not connect to trqauthd
socket_connect_unix failed: 15137

**Comment by nchernia** [comment]
We do not have a PBS cluster so I cannot debug this; however this looks like some kind of specific issue to your cluster and you should contact your IT person to see what the problem is.
