### ISSUE TITLE
The generate_site_positions.py is too slow

### ISSUE THREAD

**Issue by bioinformaticspcj** [theaidenlab/juicer#108]
Hi, thanks for writing this pipeline, it is very convenient.

But I think the "generate_site_positions.py" should be improved becuase it is time-consuming.

May be, you could choose the "index" funtion to do it 

Thanks again.

**Comment by nchernia** [comment]
There's been a rewrite of generate_site_positions that we pulled in. It is faster though not as fast as indexing. OTOH it is a piece of code that is only run once (for many thousands of runs of Juicer) .
