### ISSUE TITLE
hic scaffolding

### ISSUE THREAD

**Issue by liufuyan2016** [theaidenlab/juicer#11]
Thanks for your work on hic scaffolding . when i download the code indicated in science , but it did not existed in the website:  github.com/theaidenlab/HiC-assembly-pipeline-archive
.Could you help me?

**Comment by dudcha** [comment]
Dear liufuyan2016,

We're happy to report that the code for reproducing AaegL4 and Hs2-HiC is now available on github at github.com/theaidenlab/3d-dna. We are working to make additional code available as soon as possible.

We are happy to answer any questions at:
www.aidenlab.org/forum/

Olga
--
Olga Dudchenko, PhD
M&H Genetics/Aiden Lab
Baylor College of Medicine

**Comment by liufuyan2016** [comment]
thanks for your attention!I want to know when I could get the codes?


I have sequenced a genome, and want to use  the tools for my analysis.
Thanks!





At 2017-04-01 04:16:44, "dudcha" <notifications@github.com> wrote:


Dear liufuyan2016,

We're happy to report that the code for reproducing AaegL4 and Hs2-HiC is now available on github at github.com/theaidenlab/3d-dna. We are working to make additional code available as soon as possible.

We are happy to answer any questions at:
www.aidenlab.org/forum/

Olga

Olga Dudchenko, PhD
M&H Genetics/Aiden Lab
Baylor College of Medicine
