### ISSUE TITLE
how to make the combined .hic file

### ISSUE THREAD

**Issue by BuaaAlban** [theaidenlab/juicer#110]
How to make HIC005__merged_nodups.txt.gz and HIC006__merged_nodups.txt.gz  to a combined .hic file?
Or  how to combine HIC005.hic.gz and HIC006.hic.gz to a combined .hic file?

**Comment by nchernia** [comment]
Have a look at the mega.sh script; hic files can't be combined but you can combine the merged_nodups files via sort -m -k2,2d -k6,6d and then run Juicer Tools Pre on the resulting file.
