### ISSUE TITLE
HiCCUPSDiff

### ISSUE THREAD

**Issue by robinweide** [theaidenlab/juicer#111]
What exactly is the difference between:

1. running HICCUPS on two samples and intersecting the resulting loops?
2. running HiCCUPSDiff

I seem to get different output for these two methods. Could it be that there are lower/other thresholds used by default?

**Comment by sa501428** [comment]
Hey @robinweide ! Can you direct this question to our forum at [aidenlab.org/forum.html](http://aidenlab.org/forum.html)
