### ISSUE TITLE
"Chr" removed from the .hic file

### ISSUE THREAD

**Issue by ghuryejay** [theaidenlab/juicer#118]
Hi,

I am providing my own chrom_sizes.txt file for juicer pre to dump a .hic file. The chromosome names in my file are like "chr1, chr2, chr3,...". However in the .hic file, the chromosome names are like "1,2,3,...". Is there any way to preserve the original names in the final .hic file? I want to use the original names.

**Comment by nchernia** [comment]
@sa501428 - not sure this is possible, thoughts?

**Comment by sa501428** [comment]
@machinegun in which context do you want the chr preserved? Are you talking about the Juicebox dropdown? Straw? Some other analysis tool?

**Comment by ghuryejay** [comment]
Arrowhead and Hiccups. If I use it to call domains, the output file has chromosome names as 1,2,3... Also if the chromosome names are something else like 'contig-1', then it caps the name, so the name in arrowhead output file is like 'CONTIG-1'.

**Comment by sa501428** [comment]
This points to a broader question that I recall Olga @dudcha also had regarding what standards should be. We implemented these steps to resolve bugs when users were using different capitalizations / varying inclusion of 'chr', but all were trying to use hg19. To resolve that, we remove chr in Juicebox and capitalize everything. This allows users to load annotations/files with different labels (1, chr1, CHR1).

**Comment by ghuryejay** [comment]
Cool. Thanks!

**Comment by YichaoOU** [comment]
Hello,

How can we let juice_tools not remove `chr` and not cap the letters?

Thanks!

**Comment by sa501428** [comment]
What version of the jar are you using?

**Comment by YichaoOU** [comment]
juicer_tools_1.13.01.jar

**Comment by sa501428** [comment]
Can you try a newer jar? I recall we removed this restriction for non-human genomes.

**Comment by YichaoOU** [comment]
ok, will try, I'm using a custom genome, so I gave the program a chrom.size file, not specifying hg19.

**Comment by YichaoOU** [comment]
Hello,

I tried `1.21.01`, still chr is remove and everything is cap.

Is there a programmable way to rename the chr?

**Comment by YichaoOU** [comment]
I think I have tried all the different versions. I think I can re-compile the jar file if you can tell me which line to change.

**Comment by jeramiahsmith** [comment]
This still seems to be an issue in recent versions, Is there a fix? It makes it difficult to view Juicer output in nonhuman UCSC browsers.

**Comment by sa501428** [comment]
This issue was fixed a while back; you can grab the latest jars here: https://github.com/aidenlab/Juicebox/releases
