### ISSUE TITLE
Bug in HiCCUPSDiff: java.lang.NullPointerException

### ISSUE THREAD

**Issue by PINES-scoring** [theaidenlab/juicer#119]
Hello,

I am running into the following error with HiCCUPSDiff. I am using juicer_tools_1.11.09_jcuda.0.8.jar, and everything was run using default settings. Please let me know if you have any advice:

WARN [2019-06-22T08:40:06,645]  [Globals.java:138] [main]  Development mode is enabled
Reading file: /path/to/first/inter_30.hic
Reading file: /path/to/second/inter_30.hic
Running differential HiCCUPs with resolutions:
Config res: 5000 peak: 4 window: 7 fdr: 10% radius: 20000
Config res: 10000 peak: 2 window: 5 fdr: 10% radius: 20000
Config res: 25000 peak: 1 window: 3 fdr: 10% radius: 50000
Exception in thread "main" java.lang.NullPointerException
	at juicebox.tools.clt.CommandLineParserForJuicer.getBothNormalizationTypeOption(CommandLineParserForJuicer.java:179)
	at juicebox.tools.clt.juicer.HiCCUPSDiff.readJuicerArguments(HiCCUPSDiff.java:154)
	at juicebox.tools.clt.JuicerCLT.readArguments(JuicerCLT.java:66)
	at juicebox.tools.HiCTools.main(HiCTools.java:95)

**Comment by PINES-scoring** [comment]
Using juicer_tools_1.10.09_jcuda.0.8.jar to run HiCCUPSDiff on my two inter_30.hic files seems to execute successfully, so the problem appears to be with the latest version of Juicer Tools.

**Comment by sa501428** [comment]
what was the command used? (i.e. the full java command)

**Comment by PINES-scoring** [comment]
The command is:

java -Xms512m -Xmx2048m -jar /path/to/juicer_tools_1.11.09_jcuda.0.8.jar hiccupsdiff --cpu --ignore_sparsity /path/to/first/inter_30.hic /path/to/second/inter_30.hic /path/to/first/merged_loops.bedpe /path/to/second/merged_loops.bedpe /path/to/output/folder

Keeping exactly the same command but instead referencing juicer_tools_1.10.09_jcuda.0.8.jar works great.

**Comment by sa501428** [comment]
Resolved in the latest version
https://github.com/aidenlab/juicer/wiki/Download#version-11201
