### ISSUE TITLE
How to get final stats file(inter.txt) but skip generating .hic files?

### ISSUE THREAD

**Issue by TypicalSEE** [theaidenlab/juicer#121]
Hi, I'm using Juicer to process my Hi-C data. It seems like the final step which generates the final stats file(inter.txt) as well as .hic files will cost a very long time. So I used "-S early" option to skip this step. But I still want the inter.txt file. So what should I do to generate inter.txt? Thanks a lot!

**Comment by nchernia** [comment]
Please ask this on our forum ( aidenlab.org/forum.html )
