### ISSUE TITLE
Some bugs in mega.sh can cause errors (CPU/common/mega.sh)

### ISSUE THREAD

**Issue by longfei8533** [theaidenlab/juicer#124]
1. The default parameter `juiceDir="/aidenlab"` in the script, but this parameter cannot be modified, resulting in an error. Can it be modified like this?
```
while getopts "d:g:hxs:SD:" opt; do
    case $opt in
        g) genomeID=$OPTARG ;;
        h) printHelpAndExit 0;;
        d) topDir=$OPTARG ;;
        s) site=$OPTARG ;;
        x) exclude=1 ;;
        S) stage=$OPTARG ;;
        D) juiceDir=$OPTARG ;; ## New add
        [?]) printHelpAndExit 1;;
    esac
done
```
2. In the previous `juicer.sh` script, the default path for all other scripts is `${juiceDir}/scripts/common/`, but in this script is `${juiceDir}/scripts/`, and this will lead to errors.
3. I have meet this `Error: the chromosome combination 2_2 appears in multiple blocks`, and 
 found the reason which can be solved by changing the command `sort -T ${tmpdir} -m -k2,2d -k6,6d ${merged_names} > ${outputdir}/merged_nodups.txt` to `sort -T ${tmpdir} -m -k2,2d -k6,6d -k4,4n -k8,8n -k1,1n -k5,5n -k3,3n ${merged_names} > ${outputdir}/merged_nodups.txt` .

**Comment by nchernia** [comment]
#1 and #2 are still bugs that we should fix. For #3, you shouldn't run into that error and I'm not sure why you would have if your merged_nodups were created with Juicer originally.

**Comment by nchernia** [comment]
Fixed.

**Comment by kellyliyichen** [comment]
Hi, 

I am having the same error as 3 when running mega.sh. 

`Error: the chromosome combination 19_21 appears in multiple blocks`

By changing the command `sort --parallel=40 -T "${tmpdir}" -m -k2,2d -k6,6d ${merged_names} > "${outputDir}"/merged1.txt` to `sort --parallel=40 -T "${tmpdir}" -m -k2,2d -k6,6d -k4,4n -k8,8n -k1,1n -k5,5n -k3,3n ${merged_names} > "${outputDir}"/merged1.txt` does not solve the problem.

Another thing I could not understand is that I am analyzing mouse samples and there are only chromosomes chr1-19 and X,Y,M in my original merged1.txt, then why is there a chromosome combination 19_21?

Many thanks for the help!!

**Comment by sa501428** [comment]
@kellyliyichen please make a new thread and include more details about how you ran juicer. I think your issue is different.
