### ISSUE TITLE
-p flag for pearsons not recognised 

### ISSUE THREAD

**Issue by burnsro** [theaidenlab/juicer#131]
I have tried using the -p flag for pearsons as I wish to calculate pearsons for high resolution
I have used juicer_tools_1.10.10_jcuda0.8.jar and juicer_tools_1.13.02.jar

Running the command
java -Djava.io.tmpdir=$TMP Xmx80g -jar ~/Software/juicer/PBS/scripts/juicer_tools_1.13.02.jar pearsons -p KR ${acc}.hic 1 BP 25000 ${acc}_25Kb_pearson_1_KR.txt

Pearson's and Eigenvector are not calculated for high resolution datasets
To override this limitation, send in the "-p" flag.
WARN [2019-08-27T21:15:54,411]  [Globals.java:138] [main]  Development mode is enabled
Pearson's and Eigenvector are not calculated for high resolution datasets
To override this limitation, send in the "-p" flag.

So it seems -p is not being recognised

Running the same command but using eigenvector -p works fine and it does work, only for pearsons it is not working

**Comment by nchernia** [comment]
@sa501428 is this still an issue?

**Comment by nchernia** [comment]
@sa501428??

**Comment by burnsro** [comment]
Yes I was not able to use the -p flag for pearsons

**Comment by sa501428** [comment]
@burnsro have you tried this with the latest jar?

**Comment by burnsro** [comment]
I unfortunately no longer am looking at this data but if it works with the
updated jar then you can close this ticket, thanks

**Comment by sa501428** [comment]
This was fixed earlier this year in HiCTools.java by invoking the following for all JuiceboxCLT objects

```           
 if (parser.getAllPearsonsOption()) {
                HiCGlobals.MAX_PEARSON_ZOOM = 1;
            }
 ```
