### ISSUE TITLE
dump with -d flag creates an entire chromosome matrix even if only a specific region is requested.

### ISSUE THREAD

**Issue by moshe-olshansky** [theaidenlab/juicer#132]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Mojave, Windows 10, etc]
 - Version [e.g. 1.6]

**Additional context**

**Comment by sa501428** [comment]
I would highly recommend using https://github.com/aidenlab/straw instead of the dump command.
