### ISSUE TITLE
Is the PBS version well tested and can be used in good quality now?

### ISSUE THREAD

**Issue by LIZW2019** [theaidenlab/juicer#135]
I am a green hand in Juicer, my system is PBS and I find the PBS version exists but is not put into the overview of the software. I find that the first version was not tested in HICCUPs, but it has been updated for several times. I am wondering whether it can be used to produce acceptable output now (ignoring personal issues)? Thanks a lot to all your work!

**Comment by nchernia** [comment]
We don't have a PBS system so cannot test or debug PBS.
