### ISSUE TITLE
APA filters loops even though no filtering is specified

### ISSUE THREAD

**Issue by rikrdo89** [theaidenlab/juicer#138]
After running APA without any filtering criteria,  three values on the top of the plot are shown: filtered (2500), unique(2700), and total(2700). I am only setting the resolution (5k) and my window size. If I am not entering any threshold for distance filtering, how is it that so many of the putative loops are being filtered out? 
`juicer_tools apa -r 5000 -w 40 dmso.hic ctrl.bedpe DMSO_test`

![image](https://user-images.githubusercontent.com/24930604/67124717-2566ff80-f1c1-11e9-87ba-a7f8ef0c2c81.png)

**Comment by sa501428** [comment]
This isn't clearly a bug and should first be posted at aidenlab.org/forum.html for discussion. APA has a default `n` flag that has not been overridden and that requires loops to be a minimum pixel distance from the diagonal, so the command above would still filter loops. https://github.com/aidenlab/juicer/wiki/APA
