### ISSUE TITLE
TADS OUTPUT overlap ？

### ISSUE THREAD

**Issue by Antony-1996** [theaidenlab/juicer#139]
Dear author 
when I using TADS I encounter a problem. It's  right that the ouput TADS file have region overlapping ?hopefully I can get your reply .

**Comment by nchernia** [comment]
Overall this kind of question should be posted to the forum at aidenlab.org/forum.html

Yes, there can be domains inside domains for example; there is discussion in the supplementary materials of Rao and Huntley et al., Cell 2014.
