### ISSUE TITLE
"Invalid qos specification" & "Requested time limit is invalid"

### ISSUE THREAD

**Issue by sjfleck** [theaidenlab/juicer#143]
I'm having trouble getting the sample data to run on my university's SLURM cluster. Here's what I typically need to type in at the top of my scripts:

#!/bin/sh
#SBATCH --qos=largemem
#SBATCH --partition=largemem
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --mem-per-cpu=16000
#(tasks-per-node) * (mem-per-cpu) = GB allocated (512 for this script)
#SBATCH --job-name="juicer_install_sample_final05"
#SBATCH --output=juicer_install_sample_final05.out
#SBATCH --error=juicer_install_sample_final05.err

After setting up all the files and building the directories, I run the juicer.sh script:

cd $juicer_directory
./scripts/juicer.sh -D $juicer_directory/scripts -d $juicer_directory/HIC003 -z $juicer_directory/references/Homo_sapiens_assembly19.fasta -y $juicer_directory/restriction_sites/hg19_MboI.txt -p $juicer_directory/restriction_sites/hg19.chrom.sizes -g hg19 -s MboI -A sjfleck -t 32 -q largemem -l largemem -Q 7200 -L 7200

and I keep getting lists of errors like this:
sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)
sbatch: error: Batch job submission failed: Invalid qos specification

I've tried a few different values for -Q and -L, such as 72:00, 7200, and 72 but they all give the same errors. I'm trying to set it for 72 hours because that is the maximum time limit for 'largemem' (I'm just maxing it out for this initial run).

I'll attach my .sh, .err. and .out files below if it helps. Any insight into my problem here would be greatly appreciated! Thank you!

Files:
[juicer_install_sample_final05.txt](https://github.com/aidenlab/juicer/files/3841795/juicer_install_sample_final05.txt)
(**Note that many steps are blocked out because they have already been completed in during previous attempts)

[juicer_install_sample_final05.err.txt](https://github.com/aidenlab/juicer/files/3841798/juicer_install_sample_final05.err.txt)

[juicer_install_sample_final05.out.txt](https://github.com/aidenlab/juicer/files/3841802/juicer_install_sample_final05.out.txt)

**Comment by sa501428** [comment]
This isn't a bug and should instead be posted at aidenlab.org/forum.html
