### ISSUE TITLE
Sparse matrix warning when .hic file seems fine

### ISSUE THREAD

**Issue by emarti88** [theaidenlab/juicer#144]
Hello,

I am trying to use HICCUPS utility for loop calling on HiChIP data generated from our lab. We generated .hic file with HiCPro hic2juicebox utility on allValidPairs file. The size of the .hic file is appropriate (~3.5 Gb) and when visualized with juicebox seems to mimic previous contact maps generated from similar experiments. However, when I run the HICCUPS tool from Juicer, it warns that the data is too sparse. Using the ignore_sparsity we get very few loops. 

I was wondering if this error assumes HiC data so using a more reduced dataset like HiChIP would cause this error. Do you have any recommendations or ideas why this might be happening?

Thank you,
Eduardo

**Comment by sa501428** [comment]
Hey Eduardo!

This question should be posted to aidenlab.org/forum.html

Thanks!

**Comment by emarti88** [comment]
Understood. I submit it to the forum


Thanks!

Eduardo

________________________________
