### ISSUE TITLE
Hi-C map is too sparse to find many loops via HiCCUPS

### ISSUE THREAD

**Issue by YuhaoDoong** [theaidenlab/juicer#145]
When I tried HiCCUPS as "./scripts/common/juicer_tools hiccups ./aligned/inter_30.hic ./hiccups ", there is a warning here:
Reading file: inter_30.hic
No valid configurations specified, using default settings
Warning Hi-C map is too sparse to find many loops via HiCCUPS.
Exiting. To disable sparsity check, use the --ignore_sparsity flag.

Through JuiceBox, I think there are enough TADs in my Hi-C data, but why HiCCUPS warned that my Hi-C map is too sparse?

Any comments would be appreciated
Best.

**Comment by sa501428** [comment]
Hi @Stormsky99 , general questions should be posted to the forum as they'll be answered much more quickly there: aidenlab.org/forum.html
