### ISSUE TITLE
how to generate restriction site file with two restriction enzyme

### ISSUE THREAD

**Issue by wuxiaopei0509** [theaidenlab/juicer#148]
Hi,
I want to use 3d-dna pipeline to assemble the scaffold ,first I need to run Juicer ,How I use two enzyme in Hi-C experiment ,DpnII and MboI, How can I generate the restriction site file with generate_site_positions.py script ?
Thank you !
Best!

**Comment by sa501428** [comment]
Hi @wuxiaopei0509 , please post general questions to the forum: aidenlab.org/forum.html
