### ISSUE TITLE
How we consider the distance greater than 150 Kb? 

### ISSUE THREAD

**Issue by MamushChu** [theaidenlab/juicer#151]
I have read that the juicer tools only uses intra-chromosomal pairs with distance
greater than 300 kb to create APA plots by default. Here I want to change the 300 kb distance to 150 kb. But, I could not find any options that changes this value. Therefore, would you please tell me some hint how I consider the distance greater than 150 Kb?

**Comment by nchernia** [comment]
@msshamim ?

**Comment by nchernia** [comment]
@sa501428

**Comment by sa501428** [comment]
See the `-n` flag here 
https://github.com/aidenlab/juicer/wiki/APA#detailed-usage
Also, please post general questions to aidenlab.org/forum.html
