### ISSUE TITLE
juicer_tool version 1.14.08 hiccups [--ignore_sparsity] flag not recognized

### ISSUE THREAD

**Issue by zhang-adam** [theaidenlab/juicer#153]
Hi,

I was trying to use jucier_tool version 1.14.08 hiccups to call loops in my hi-c data. The software gave me a warning of sparse data and asked me to enable the --ignore_sparsity flag. But when I tried it, this version of software doesn't recognize the flag:

error code:

Exception in thread "main" jargs.gnu.CmdLineParser$UnknownOptionException: Unknown option '--ignore_sparsity'
	at jargs.gnu.CmdLineParser.parse(CmdLineParser.java:475)
	at jargs.gnu.CmdLineParser.parse(CmdLineParser.java:426)
	at juicebox.tools.HiCTools.main(HiCTools.java:61)

I wonder is this a bug ? Can it be fixed ?

Thanks

**Comment by sa501428** [comment]
Hi, yes this is a bug. You can use `--ignore-sparsity` for the moment.
Some usage flags were updated and merged in prior to updates to the documentation.

To clarify though, unless you have sufficient depth, the map is not likely to find loops. `--ignore-sparsity` does not enable any special options but merely runs HiCCUPS anyways to see what the resulting calls will be.

**Comment by nchernia** [comment]
Please don't use this jar, we found it had several major issues.
