### ISSUE TITLE
dump error

### ISSUE THREAD

**Issue by xiaowenchenjax** [theaidenlab/juicer#167]
**Are you sure this is a bug?**
If unsure, please post your question/situation to the forum first: aidenlab.org/forum.html

**Describe the bug**
running "java -jar juicer_tools_1.19.02.jar dump observed KR inter_30.hic 1 1 BP 100000 SCI_input.txt"
the error :
"WARN [2020-05-12T15:04:55,107]  [Globals.java:138] [main]  Development mode is enabled
Exception in thread "main" java.lang.NullPointerException
	at juicebox.tools.clt.old.Dump.extractChromosomeRegionIndices(Dump.java:454)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:323)
	at juicebox.tools.HiCTools.main(HiCTools.java:93)"
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Mojave, Windows 10, etc]
 - Version [e.g. 1.6]

**Additional context**

**Comment by Gonysh** [comment]
I'm experiencing the same issue with juicer_tools_1.21.01, running on Ubuntu 14.04.

**Comment by nchernia** [comment]
@sa501428

**Comment by sa501428** [comment]
@Gonysh @xiaowenchenjax can you share a link to a hic file which is failing this command?

**Comment by sa501428** [comment]
I would highly recommend using https://github.com/aidenlab/straw instead of the dump command.
