### ISSUE TITLE
juicer//scripts/common/collisions_dedup_rearrange_cols.awk:19: fatal: 3 is invalid as number of arguments for asort

### ISSUE THREAD

**Issue by forrwill** [theaidenlab/juicer#172]
my scripts errors with the information of "juicer//scripts/common/collisions_dedup_rearrange_cols.awk:19: fatal: 3 is invalid as number of arguments for asort", and what's the reason of the error

**Comment by forrwill** [comment]
and my collision.txt is empty, and I don't know why

**Comment by forrwill** [comment]
users  538 Jul  7 18:07 header
users  78G Jul  8 03:25 merged_sort.txt
users 169M Jul  8 04:40 opt_dups.txt
users  44G Jul  8 04:40 dups.txt
users  34G Jul  8 04:40 merged_nodups.txt
users 1.4K Jul  8 04:46 inter_30.txt
users 1.9K Jul  8 05:03 inter.txt
users  15K Jul  8 05:03 inter_hists.m
users 8.6G Jul  8 05:05 abnormal.sam
users 7.7G Jul  8 05:07 unmapped.sam
users    1 Jul  8 05:12 collisions_nodups.txt
users    1 Jul  8 14:10 collisions.txt
users 326M Jul  8 14:17 inter.hic

**Comment by nchernia** [comment]
This error is due to your awk / gawk being an older version.  It should be at least 4.0.2.

As for no collisions, this can happen if you don't have mapq >= 10 reads in your "abnormal.sam" file.
