### ISSUE TITLE
Loop list is empty or incorrect path provided error for APA

### ISSUE THREAD

**Issue by awezmm** [theaidenlab/juicer#174]
I am trying to use the apa function like this:
java -jar ../juicer_tools.1.8.9_jcuda.0.8.jar apa my.hic my.bedpe outdirectory
and I keep getting the error "Loop list is empty or incorrect path provided."

The apa page says that the peaks file can be in standard 2d feature format which links to the bedpe file format.
I have checked that my bedpe file is tad delimited and has a header line but I still get the error.

I have even tried copying and pasting the backwards compatibility example given on the 2d feature format page as the input peak file to apa but I still get the same "Loop list is empty or incorrect path provided." error.

I am confused on what this error means and why my format for the peak file is incorrect.
Thank you

**Comment by zhengdafangyuan** [comment]
I have the same problem, did you solve this problem and can anyone give some help?

`java -Xmx20g -jar ~/Juicebox/juicer_tools_1.22.01.jar apa -r 10000 -c chr2 /data1/4DNFI1UEG1HD.hic all_loops.txt Result_dir
  
ResultWARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARN [2022-01-11T19:58:16,606]  [Globals.java:138] [main]  Development mode is enabled
Reading file: /data1/4DNFI1UEG1HD.hic
Processing APA for resolution 10000
Loop list is empty or incorrect path provided.`


the head of my all_loops.txt file : 
```
#chr1	x1	x2	chr2	y1	y2	name	score	strand1	strand2	color
chr1	153507524	153517524	chr1	153747524	153757524	1	100	+	+	255,0,0
chr1	153507524	153517524	chr1	153977524	153987524	2	100	+	+	255,0,0
chr1	184070866	184080866	chr1	184660866	184670866	3	100	+	+	255,0,0
chr1	184070866	184080866	chr1	184220866	184230866	4	100	+	+	255,0,0
chr1	204560872	204570872	chr1	204760872	204770872	5	100	+	+	255,0,0
chr1	147258346	147268341	chr1	147638201	147648198	6	100	+	+	255,0,0
chr1	147268341	147278328	chr1	147887873	147897870	7	100	+	+	255,0,0
chr1	236756700	236766700	chr1	237376700	237386700	8	100	+	+	255,0,0
chr1	119277377	119287377	chr1	119357377	119367377	9	100	+	+	255,0,0
```

**Comment by awezmm** [comment]
Hey, can you check if it works with just this head? Like make a separate file with just these lines you have here and see if it works?

**Comment by sa501428** [comment]
Let's move this discussion to: https://groups.google.com/g/3d-genomics/c/HgAutWVEHms
