### ISSUE TITLE
producing raw interaction frequency matrices from .hic

### ISSUE THREAD

**Issue by rdali** [theaidenlab/juicer#175]
Hello, 

I saw that juicer can produce O/E pearson matrices from .hic files using the "pearson" module. However, I am interested in getting the raw IF matrices from the .hic files. Can juicer produce those?

Thank you!

**Comment by sa501428** [comment]
Are you looking for this: https://github.com/aidenlab/Juicer/wiki/Data-Extraction

Also, general questions are preferred on the forum and help serve as FAQs that way: https://aidenlab.org/forum.html

**Comment by rdali** [comment]
Noted about the forum.

That is exactly what I needed. Thank you!
