### ISSUE TITLE
how to choose the Job scheduling system form LSF,PBS and so on

### ISSUE THREAD

**Issue by shiyi-pan** [theaidenlab/juicer#177]
hi, I want to do some practise about Hi-C data, my server is SGE system and I don't know which system is suit for me in the list you provided. could give me some advise? Thanke you very much.

**Comment by nchernia** [comment]
Hello,
For SGE, you should look at UGER, though you will have to modify it to work with your system. You also should search the forum for advice (aidenlab.org/forum.html)

**Comment by shiyi-pan** [comment]
hi，thank you for your reply , when I run the juicer in UGER, I got an error :
Unable to run job: denied: host "compute-0-1.local" is no submit host.
could you give me some advise to fix it?
