### ISSUE TITLE
Problem about calculate_map_resolution.sh

### ISSUE THREAD

**Issue by QianzhaoJ** [theaidenlab/juicer#178]
Hi,
   I want to use  `calculate_map_resolution.sh` to determine the map resolutions ,but I don't have th merged_nodups files because I used `HiCPro` pipeline to generate interaction matrix and coverted validPairs to the `.hic` files, how can I use the `calculate_map_resolution.sh` by `hic` files or Can I convert the `validPairs ` to merged_nodups files ? and I can coverted validPairs to the `Medium format just like:

`readname> <str1> <chr1> <pos1> <frag1> <str2> <chr2> <pos2> <frag2> <mapq1> <mapq2>` 

Perhaps I can use this intermediate file the use `calculate_map_resolution.sh` ?
   Thanks in advance !
Best wishes
Qianzhao

**Comment by nchernia** [comment]
Unfortunately, you need the actual position, not just the binned sums, to properly determine your map resolution. From Rao & Huntley, et al. Cell 2014: "We define the ‘‘map resolution’’ as the smallest locus size such that 80% of loci have at least 1,000 contacts. The map resolution is meant to reflect the finest scale at which one can reliably discern local features."

From already binned maps, you could never have a map resolution below your lowest binned resolution.

If validPairs gives the position of each read, you could potentially convert it to merged_nodups.

For follow up questions, please post to the forum at aidenlab.org/forum.html

**Comment by Gemma-Zhang-326** [comment]
> Hi, I want to use `calculate_map_resolution.sh` to determine the map resolutions ,but I don't have th merged_nodups files because I used `HiCPro` pipeline to generate interaction matrix and coverted validPairs to the `.hic` files, how can I use the `calculate_map_resolution.sh` by `hic` files or Can I convert the `validPairs ` to merged_nodups files ? and I can coverted validPairs to the `Medium format just like:
> 
> `readname> <str1> <chr1> <pos1> <frag1> <str2> <chr2> <pos2> <frag2> <mapq1> <mapq2>`
> 
> Perhaps I can use this intermediate file the use `calculate_map_resolution.sh` ? Thanks in advance ! Best wishes Qianzhao

Hi, I encounter the same issue with you. I wonder if you have solved the problem? Many thanks!

**Comment by sa501428** [comment]
Hi @Gemma-Zhang-326, please see Neva's answer. In order to calculate the resolution, the actual position, not the summed bins, is needed.

**Comment by Gemma-Zhang-326** [comment]
> Hi @Gemma-Zhang-326, please see Neva's answer. In order to calculate the resolution, the actual position, not the summed bins, is needed.

I see...... Thanks a lot.
