### ISSUE TITLE
Juicer pre create .hic

### ISSUE THREAD

**Issue by BenxiaHu** [theaidenlab/juicer#188]
Hi,
  I also follow this command to run jucer to create a .hic file
  `java -Xmx2g -jar juicebox_tools.jar pre data/test.txt.gz data/test.hic hg19`

I want to know what kind of normalization is used by the above-mentioned command.

if not, can I apply ICE to normlize the .hic file generated by   _`java -Xmx2g -jar juicebox_tools.jar pre`_

**Comment by sa501428** [comment]
Vanilla Coverage (VC), Square Root of Vanilla Coverage (VC_SQRT), and actual matrix balancing (KR or SCALE).
Please use the forum (aidenlab.org/forum.html for general questions)
