### ISSUE TITLE
How to solve  No reads in Hi-C contact matrices error?

### ISSUE THREAD

**Issue by gitcruz** [theaidenlab/juicer#193]
Dear Olga,

I am running Juicer v1.6 on. a fairly contiguous genome assembly (N50 76.6Mb) using HiC reads generated with the DNase protocol. Thus I ran it with the -s option specifying none, like this:

/scratch/project/devel/aateam/src/juicer1.6/SLURM/scripts/juicer.sh -g $name -s none -p $CWD/references/$name.chrom.sizes -z $CWD/references/$name.fa -t 24

However, I never get proper .hic files (I cannot visualize the contacts with JuiceBox). And the hic errors say:

more debug/hic-26426085.err
load java/1.8.0u31 (PATH, LD_LIBRARY_PATH)
Picked up _JAVA_OPTIONS: -Xmx98304m -Xms98304m
java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.
	at juicebox.tools.utils.original.MatrixZoomDataPP.mergeAndWriteBlocks(MatrixZoomDataPP.java:276)
	at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:970)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:659)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:425)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:139)
	at juicebox.tools.HiCTools.main(HiCTools.java:94)

One thing I noticed is that there are lot of PCR duplicates reported, but not everything is below the MAPQ threshold it seems that at least 12.9% are valid HiC contacts...
Alignable (Normal+Chimeric Paired): 129,189,170 (93.78%)
Unique Reads: 22,579,844 (16.39%)
PCR Duplicates: 106,572,249 (77.36%)
Optical Duplicates: 37,077 (0.03%)
Library Complexity Estimate: 22,655,598
Intra-fragment Reads: 0 (0.00% / 0.00%)
Below MAPQ Threshold: 4,804,484 (3.49% / 21.28%)
Hi-C Contacts: 17,775,360 (12.90% / 78.72%)

 I have also checked if the merge_nodups.txt contains reads and is not empty. And actually that is the case and this file looks fine.

Any idea on how to solve this issue? Should I upgrade java, perhaps?

Thanks in advance,
Fernando

**Comment by wuxingbo1986** [comment]
Hi @gitcruz 
Just wondering if you resolved this or not, I am having the same issue. Thanks.

**Comment by sa501428** [comment]
This should be moved to the forum / similar questions have been answered there. aidenlab.org/forum.html
