### ISSUE TITLE
how to set resolution  in hiccups

### ISSUE THREAD

**Issue by shiyi-pan** [theaidenlab/juicer#198]
Hi，I run the juicer_tools with following command:

java -jar $JUICER/CPU/common/juicer_tools.jar hiccups --cpu --threads 4 -r 100000 --ignore-sparsity $DIR/aligned/inter_30.hic inter_30.hic.hiccups

but the command seems not do the work at the resolution  of 100000  bp ,here is the logs:
 
Reading file: /ds3512/home/panyp/NN1138-2/HiC/06.juicer_hic_data/aligned/inter_30.hic
Discarding invalid configuration: Config res: 100000 peak: -1 window: -1 fdr: 10% radius: -1
No valid configurations specified, using default settings
WARNING - You are using the CPU version of HiCCUPS.
The GPU version of HiCCUPS is the official version and has been tested extensively.
The CPU version only searches for loops within 8MB (by default) of the diagonal and is still experimental.
Using 4 CPU thread(s)
Warning Hi-C map is too sparse to find many loops via HiCCUPS.
Default settings for 5kb, 10kb, and 25kb being used
Running HiCCUPS for resolution 5000
Data not available for SCAFFOLD_145 at 5000 resolution
Data not available for SCAFFOLD_21 at 5000 resolution
4%
9%
14%
19%
24%

could you tell me what's wrong with my command?  Thank you very much.

**Comment by sa501428** [comment]
This has been answered on the forum: aidenlab.org/forum.html
In short, when choosing a custom resolution outside of 5000/10000/25000 - you must specify all flags https://github.com/aidenlab/juicer/wiki/HiCCUPS#defaults
