### ISSUE TITLE
whole-genome addNorm running for a very long time

### ISSUE THREAD

**Issue by SooLee** [theaidenlab/juicer#199]
**Describe the bug**
juicer_tools.jar addNorm (1.8.9) on an old zebrafish hic file (generated by 1.8.9) fails to converge and runs for weeks on 1kb resolution with whole genome option (-w). It goes through without whole genome normalization and it runs fine for other lower resolutions. It's not memory issue (it's using ~10G mem consistently and I have 64G on my machine). I have tried a few latest versions but they all produce this kind of error below:
```
 WARN [2020-12-14T14:36:44,329]  [Globals.java:138] [main]  Development mode is enabled
Exception in thread "main" java.lang.NullPointerException
	at juicebox.tools.clt.old.AddNorm.readArguments(AddNorm.java:88)
	at juicebox.tools.HiCTools.main(HiCTools.java:93)
```
Is this an already fixed bug? If it is, is there a compatibility issue for old files?

Thanks!

**To Reproduce**

1. get out.hic file from https://soos-4dn-bucket.s3.amazonaws.com/zebrafish-pairs-troubleshooting/out.hic
2. `java -Xmx32g -Xms32g -jar juicer_tools.1.8.9_jcuda.0.8.jar addNorm -w 1000 -d -F out.hic`
It keeps running at resolution 1000.
3. `java -Xmx32g -Xms32g -jar juicer_tools.1.8.9_jcuda.0.8.jar addNorm -w 500000 -d -F out.hic`
This one runs fine. So I think it's just whole-genome.
4. `java -Xmx32g -Xms32g -jar juicer_tools_1.19.02.jar addNorm -w 1000 -d -F out.hic`
This one shows the following error:
```
WARN [2020-12-14T14:36:44,329]  [Globals.java:138] [main]  Development mode is enabled
Exception in thread "main" java.lang.NullPointerException
	at juicebox.tools.clt.old.AddNorm.readArguments(AddNorm.java:88)
	at juicebox.tools.HiCTools.main(HiCTools.java:93)
```
5.  `java -Xmx32g -Xms32g -jar juicer_tools_1.19.02.jar addNorm -w 1000 -d -F -k VC,VC_SQRT,KR,GW_KR out.hic`
Same error.
6. `java -Xmx32g -Xms32g -jar juicer_tools_1.19.01.jar addNorm -w 1000 -d -F -k VC,VC_SQRT,KR,GW_KR out.hic`
Same error.

**Expected behavior**
The normalization should finish within a day or so (instead of weeks), like other zebrafish hic files that we have that are of similar sizes.

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04

**Comment by sa501428** [comment]
Hey @SooLee! I will try running this with the file you provided. Just a quick check - did you also try with version 1.22.01? https://github.com/aidenlab/juicer/wiki/Download#version-12201

**Comment by SooLee** [comment]
@sa501428 Thanks for the quick reply. I didn't try 1.22.01 because it said 'dev' version.

**Comment by SooLee** [comment]
@sa501428 I'm trying 1.22.01 and it's running (at least not getting the error I got with 1.19.01)
`java -Xmx32g -Xms32g -jar /usr/local/bin/juicer_tools_1.22.01.jar addNorm -w 1000 -d -F /e/data/zebrafish-pairs-troubleshooting/out.hic`
I will let you know how it goes with 1kb res. Thanks!

**Comment by SooLee** [comment]
@sa501428 with 1.22.01, I still get this thing running for a while. I also noticed that actually with `-w 500000` it has the same problem (previously it got accidentally aborted, was not completed successfully). It's not necessarily genome-wide normalization but any normalization? It could be a convergence problem? Can you try it? Thanks!

**Comment by sa501428** [comment]
Resolved with newest jars.
