### ISSUE TITLE
juicer.sh SLURM script

### ISSUE THREAD

**Issue by keagen** [theaidenlab/juicer#2]
Discovered on lines 407 and 452 code is:

`if [ -v shortread ] || [ "$shortreadend" -eq 1 ]`

but getting a

`[: -v: unary operator expected` error

I'm guessing this needs to be changed to:
`if [ -v $shortread ] || [ "$shortreadend" -eq 1 ]`

to call the $shortread variable.  Can you please check this?

**Comment by imachol** [comment]
Oh, this is bash version dependent issue.
Were checking if variable is defined, not empty.

If it does not work for you, try
[ -z ${shortread+x} ]
Instead.

**Comment by keagen** [comment]
Ok.  That fixed the error message.

Looking at the debug files for the alignment it is running `bwa aln` and not `bwa mem`, though I didn't change anything else in the juicer.sh script to tell it to do short read alignment.  Is this normal?

In case related to the version of bash I am running:

```
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by imachol** [comment]
The check is working now, but is actually opposite to what you need - 

try [ ! -z ${shortread+x} ] instead.

-v will return 1 if variable is unset, and 0 if it is set.

-v is only supported in version > 4.2, so I really recommend upgrading, or setting the value explicitly.

Ido

**Comment by keagen** [comment]
Great!  Yes, it's working now.  Thanks for all your help!

Kyle
