### ISSUE TITLE
CPU threads flag

### ISSUE THREAD

**Issue by aakashsur** [theaidenlab/juicer#20]
I'm using AWS EC2 instances, and I was wondering how I can utilize more than one cpu (which is how I assume the cpu "version" works). Was there something like a --threads flag? I also noticed the AMI for Juicer is for version 1.06, so I decided to install it on a fresh instance instead.

**Comment by sa501428** [comment]
Hey @aakashsur 

For AWS EC2, it would be best to use the AMI. We have instructions for updating with the latest scripts here:
https://github.com/theaidenlab/juicer/wiki/Running-Juicer-on-Amazon-Web-Services

Specifically these lines:
```
cd ~
wget https://github.com/theaidenlab/juicer/archive/master.zip
unzip master.zip
sudo cp -TR juicer-master/AWS/scripts /opt/juicer/scripts
```
under [first time tweaks](https://github.com/theaidenlab/juicer/wiki/Running-Juicer-on-Amazon-Web-Services#first-time-tweaks)

Also, it would be best to post this question to the forum
http://aidenlab.org/forum.html

**Comment by aakashsur** [comment]
Gotcha, missed that part. Thanks!

**Comment by theaidenlab** [comment]
FYI this has since changed, and you can use "-t" to set threads if you want to run the CPU version on your own image instead of going through ours.
