### ISSUE TITLE
AWS image ami-458fc22f does not exist

### ISSUE THREAD

**Issue by ArielPaulson** [theaidenlab/juicer#210]
Hi,

I mentioned this a month ago, as a comment on the issue post of the last guy who had this issue.  I'll open a new issue this time.
  
I was following the directions at https://github.com/theaidenlab/juicer/wiki/Running-Juicer-on-Amazon-Web-Services, which say to launch image ami-458fc22f which should be found in "Community AMIs".  It does not exist there, nor in the Marketplace, nor does a search for "juicer" bring up anything.  I am in the US East Ohio zone.

Steps:

Log into AWS > EC2 Dashboard > Launch Instance > Launch Instance > Community AMIs > Search for "ami-458fc22f" 

Results:

"No results were found for "ami-458fc22f" in the Community AMIs catalog.
The following results for "ami-458fc22f" were found in other catalogs:
4835 results in AWS Marketplace"

None of the AWS marketplace hits appears to be the actual AMI, though.  At any rate I cannot scroll through 4835 hits 10 at a time to see if any are the required AMI.  Searching for "juicer" or "GPU" likewise returns nothing of interest.

Thanks,
Ariel

**Comment by sa501428** [comment]
The AMI should be visible if you switch to US-East-1 (Virginia)
@weiszd we should get this copied to the other regions though.

**Comment by weiszd** [comment]
Here are the copies for two additional regions:
ami-03967083204a71d76 - US West (Oregon)us-west-2
ami-0cf958a247826ffa0  - US East (Ohio)us-east-2

**Comment by sa501428** [comment]
Thanks @weiszd !!
