### ISSUE TITLE
GPUs are not installed so HiCCUPs cannot be run

### ISSUE THREAD

**Issue by yuan102379** [theaidenlab/juicer#211]
Hi everyone,

Now, I am running the Juicer, while I meet a problem. Due to the problem, I can not get the desired map.

The log information at the last Juicer log file is followed: 

"
HiCCUPS:

**GPUs are not installed s**o HiCCUPs cannot be run

(-: Postprocessing successfully completed, **maps too sparse to annotate or GPUs unavailable** (-:

"
So what should I do?

Could you give me some suggestions, please?

Look forward to your response and Best wishes!

Yours,

Yuan

**Comment by sa501428** [comment]
Hi Yuan,
Please use the Google Forum for general questions: https://groups.google.com/g/3d-genomics
Github issues is just for bugs.

Options:
- use HiCCUPS-CPU
- use a GPU instance on Google Colab/AWS/etc.
See this thread: https://groups.google.com/g/3d-genomics/c/I8TOxv3po6U

**Comment by nothingisimpossib** [comment]
I met the same question

**Comment by H1207953831** [comment]
I met the same question too, but I can not visit the url:https://groups.google.com/g/3d-genomics

**Comment by Summer0lhl** [comment]
> I met the same question too, but I can not visit the url:https://groups.google.com/g/3d-genomics

I also met same problem. Have you deal with this problem ?
