### ISSUE TITLE
 juicer_tools.jar dump creates a dense matrix bigger than the requested limits

### ISSUE THREAD

**Issue by jazberna1** [theaidenlab/juicer#212]
**Are you sure this is a bug?**
I believe this is a bug, already mentioned here:
https://github.com/aidenlab/juicer/issues/132

**Describe the bug**
The juicer juicer_tools.jar dump command  seems to create a matrix bigger than the requested limits when used with the -d (dense) flag.

**To Reproduce**
run the example provided in https://github.com/aidenlab/juicer/wiki/Data-Extraction adding the -d flag:

`java -jar juicer_tools.jar dump observed KR https://hicfiles.s3.amazonaws.com/hiseq/gm12878/in-situ/combined.hic 1:20480000:40960000 1:20480000:40960000 BP 10000 combined_10Kb.txt -d`

Then plotting the resulting matrix combined_10Kb.txt gives the attached jpg where there is a portion of the image surrounding the requested limits.

**Expected behavior**
I expected to get an image restricted to  1:20480000:40960000

**Screenshots**
![combined_10Kb](https://user-images.githubusercontent.com/27732589/111458439-b5440c80-8719-11eb-82a9-e19c2913531d.jpg)

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server
 - Version 7.5 (Maipo)
 My Juicer Tools Version is 1.19.02

**Additional context**
Many thanks!
Jorge

**Comment by sa501428** [comment]
I would highly recommend using https://github.com/aidenlab/straw instead of the dump command.
