### ISSUE TITLE
Typo in sam_to_mnd

### ISSUE THREAD

**Issue by DustinSokolowski** [theaidenlab/juicer#226]
Hey! 

Thank you for the fantastic tool. I just wanted to let you know that there is a small typo in sam_to_mnd (https://github.com/aidenlab/juicer/blob/encode/CPU/common/sam_to_mnd.sh). Instead of samtools you have saamtools.

Best!
Dustin

`

**Comment by nchernia** [comment]
Thanks fixed with fce5b1f
