### ISSUE TITLE
what's the difference between "unique" and "inferred" folders when using MotifFinder? 

### ISSUE THREAD

**Issue by hzjsxu** [theaidenlab/juicer#227]
When finding DNA motifs for loops using motifs command in the juicer_tools, there is a question confusing that what's the difference between files under "unique" and "inferred" folder ? For example, there are two CTCF-related bed files under these folders, what's the difference between these two files and How can I get these files ?

![image](https://user-images.githubusercontent.com/45815139/122392820-cdd8f280-cfa6-11eb-9f60-cb13558e8e58.png)

![image](https://user-images.githubusercontent.com/45815139/122392694-aeda6080-cfa6-11eb-9f34-83da65c3566a.png)

I will greatly appreciate it if you guys can give us some suggestions to fix those issues!

**Comment by sa501428** [comment]
Hi @hzjsxu,
I updated the clarification here: https://github.com/aidenlab/juicer/wiki/MotifFinder#usage
You can run the code for GM12878 through Colab here: https://github.com/aidenlab/juicer/wiki/MotifFinder#examples
See Section VI.e.7 of the Extended Experimental Procedures of Rao, Huntley et al. Cell 2014 for more details.
Also please use the forum for general questions and the Github for bugs.

**Comment by bio-lijs** [comment]
That means the CTCF bed files under unique folder is generated by intersecting several replicates, while the other one under the inferred folder is a union of replicates. isn`t it?

**Comment by sa501428** [comment]
Essentially yes, you could do that with narrowpeak bed files for the respective folders.
 
For the exact GM12878 bed files, the procedure should be documented in Section VI.e.7 of the Extended Experimental Procedures of Rao, Huntley et al. Cell 2014. The colab notebook also has links to download them.
