### ISSUE TITLE
how to read these informations on the dump(data extraction) from .hic documnet

### ISSUE THREAD

**Issue by tyewaichung** [theaidenlab/juicer#246]
hello!teacher:
how to read these informations on the dump(data extraction) from .hic documnet?
I get data through dump  from .hic doucement,but i am not able to  read these informations.
just like this 
990000	43050000	1
1000000	43050000	1
1900000	43050000	1
2440000	43050000	1
4060000	43050000	1
6680000	43050000	1
7560000	43050000	1
7680000	43050000	1
8550000	43050000	1
8670000	43050000	1
8770000	43050000	1
8890000	43050000	1
9120000	43050000	1
9250000	43050000	1
9490000	43050000	1
1020000	43060000	1

**Comment by sa501428** [comment]
Discussion moved to https://groups.google.com/g/3d-genomics/c/Euvir4CULB0/m/NRYHRtFXAQAJ
