### ISSUE TITLE
can not use custom resolution

### ISSUE THREAD

**Issue by LinXialab** [theaidenlab/juicer#248]
Hi,

When I use the follow command line to call loops with the custom resolution, I only get results called with the default resolution, could you please help me to solve this problem?

juicer_tools_1.11 hiccups --ignore_sparsity  --cpu --threads 24 -m 512 -r 40000 -k KR -f 0.1 -p 1 -d 80000 -i 2 allValidPairs.hic hiccups_results1/

the comments are as follow:

WARN [2021-11-16T11:02:07,572]  [Globals.java:138] [main]  Development mode is enabled
Reading file: Unknown_AK096-02H0001_good.allValidPairs.hic
**Resolution 40000 not available.**
No valid configurations specified, using default settings
WARNING - You are using the CPU version of HiCCUPS.
The GPU version of HiCCUPS is the official version and has been tested extensively.
The CPU version only searches for loops within 8MB (by default) of the diagonal and is still experimental.
Using 24 CPU threads
Warning Hi-C map is too sparse to find many loops via HiCCUPS.
Default settings for 5kb, 10kb, and 25kb being used
Running HiCCUPS for resolution 5000

Looking forward your reply!

**Comment by moshe-olshansky** [comment]
Hi,
You can do
juicer_tools_1.11 validate allValidPairs.hic 
to see the list of available resolutions in your .hic file and you can call loops for those resolutions only. Try 50000 instead of 40000.
