### ISSUE TITLE
Default branch explanation

### ISSUE THREAD

**Issue by Zojka** [theaidenlab/juicer#253]
Hi Team,
Could you please clarify why (and when) have you decided to change the default branch from master to encode?
Does the master contain any concerning bugs or issues?
I noticed that the wiki has not changed and samtools are missing from the dependencies list. Do you remember any other points in the wiki that might be missing (or became obsolete) since the switch?

Best,

Zofia

**Comment by sa501428** [comment]
Hi @Zojka !

We're making a push to release Juicer 2 soon, which is on the encode branch. It's not that the previous master branch was wrong, but we've been working on lots of improvements. We do plan to update the wiki. You can download the source code for Juicer 1.6 from the releases: https://github.com/aidenlab/juicer/releases/tag/1.6

**Comment by sa501428** [comment]
README has been updated. Closing issue.
