### ISSUE TITLE
Straw successfully dumps data, but juicer_tools.jar fails

### ISSUE THREAD

**Issue by ArielPaulson** [theaidenlab/juicer#266]
I have several hic files, and when dumping data for certain chromosomes / bin sizes, juicer_tools.jar (even the most recent) will fail, while the equivalent 'straw' command returns the expected data.

For instance this command fails:
java -jar juicer_tools.jar dump oe KR $myHicFile 10 10 BP 5000    # 100% "nan"

But this equivalent command succeeds:
straw oe KR $myHicFile 10 10 BP 5000    # all normal data

I am using the latest straw build (just a few days ago), versus two different juicer tools versions, both juicer_tools.jar v1.22.01 and feature_tools.jar v2.14.00.

Thanks,
Ariel

**Comment by sa501428** [comment]
Hey Ariel!
Our plan is to deprecate dump in favor of straw, which supports C++, Java, Python, R, and MATLAB. Is there a use case where dump does something that straw cannot do? (if so, we can aim to add that feature to straw)

**Comment by ArielPaulson** [comment]
Hi Muhammad,

No that I know of.  If the plan is to replace dump then everything is ok, just make sure all the wiki instructions get updated!

Thanks,
Ariel

**Comment by sa501428** [comment]
Will do, thanks!
