### ISSUE TITLE
Creating .hic from bedpe using Pre

### ISSUE THREAD

**Issue by cgirardot** [theaidenlab/juicer#270]
Dear,
This is a question regarding the creation of .hic files from binned data. 

I used to create .hic from bedpe file eg 
```
chr2L	5000	10000	chr2L	5000	10000	26
chr2L	5000	10000	chr2L	10000	15000	1
chr2L	5000	10000	chr2L	30000	35000	1
chr2L	5000	10000	chr2L	40000	45000	1
chr2L	5000	10000	chr2L	60000	65000	3
chr2L	5000	10000	chr2L	70000	75000	1

```

but I cant see bedpe being supported anymore https://github.com/aidenlab/juicer/wiki/Pre#file-format. I am still using  juicer_tools_1.11.09_jcuda.0.8.jar for this and it seems to work. 

Have you dropped support for `bedpe` in recent releases? 

Thx

**Comment by sa501428** [comment]
Bedpe was never a supported format for making .hic files. 
You'll want to convert to one of the accepted formats.
We use the bedpe format for saving loops, domains, etc.

**Comment by cgirardot** [comment]
ohhhh I am sorry, my bad. I indeed convert the bedpe on the fly to "Short with score format". Sorry for wasting your time and thank you for being my rubber duck!

**Comment by sa501428** [comment]
No worries! :)
