### ISSUE TITLE
Dups/no dups error

### ISSUE THREAD

**Issue by tonyjhlam** [theaidenlab/juicer#271]
I am seeing the following error at the dupcheck phase:
 ***! Error! The sorted file and dups/no dups files do not add up, or were empty.

Running multiple samples, but only one sample produces this error. What might be a contributing factor to this error, and how can I debug?

**Comment by sa501428** [comment]
Hi, please see this thread: https://groups.google.com/g/3d-genomics/c/G386jQXD8RU/m/2H7IGZKwAwAJ

**Comment by tonyjhlam** [comment]
@sa501428 I am running the SLURM version of juicer. The jobs stall at dupcheck, and do not begin processes/jobs past this stage due to dependencies not met. 

This issue is different than the issue linked, as I do not get any files past the merged_dedup.sam file.
