### ISSUE TITLE
No files in the split folder and the basename problem

### ISSUE THREAD

**Issue by ala98412** [theaidenlab/juicer#287]
Hi there,

I am trying on a Yeast genome for _denovo_ assembly, using juicer on CPU version.
I have few questions here.

1. I used the -z option and input my own genome file, why the program still aligning to the genome hg19? Am I doing something wrong?
2.  I don't have any files in the splits folder.
3. What is "basename" do for? And what wrong is happening?

I've created a folder named "fastq" in the folder "topDir", and I have fastq files inside the folder.
All files and folders in the "CPU" folder were copied to the folder "scripts" in my current folder.

My command and the error messages is below:

**$ ./scripts/juicer.sh -z ./genome/MYA3404.genome.fa -d ./topDir/ -p assembly -D ./**
(-: Looking for fastq files...fastq files exist
(-: Aligning files matching ./topDir//fastq/*_R*.fastq*
 to genome hg19 with site file .//restriction_sites/hg19_none.txt
---  Using already created files in ./topDir//splits

**basename**: extra operand './topDir//splits/**.fastq.gz_norm.txt.res.txt'
Try 'basename --help' for more information.
gzip: ./topDir//splits/*_R1*.fastq.gz: No such file or directory
gzip: ./topDir//splits/*_R2*.fastq.gz: No such file or directory
gzip: ./topDir//splits/*_R1*.fastq.gz: No such file or directory
bwa mem -SP5M -t 12 ./genome/MYA3404.genome.fa ./topDir//splits/*_R1*.fastq.gz ./topDir//splits/*_R2*.fastq.gz > ./topDir//splits/**.fastq.gz.sam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[E::main_mem] fail to open file `./topDir//splits/*_R1*.fastq.gz'.
***! Alignment of ./topDir//splits/*_R1*.fastq.gz ./topDir//splits/*_R2*.fastq.gz failed.

Thanks for your kindly helping !

ala98412

**Comment by sa501428** [comment]
Hi @ala98412,
Please post general questions to the forum: https://groups.google.com/g/3d-genomics
