### ISSUE TITLE
aligned/merged1.txt does not exist or does not contain any reads.

### ISSUE THREAD

**Issue by 1580542426** [theaidenlab/juicer#294]
When I use HiC to help assemble genome, I run the following code:
/ME4012_Vol0002/Ahome_Dir/hechuanmeng/SY_genome/SY_genome/sanya_genome/raw_data/3d-DNA/juicer/scripts/juicer.sh -t 30 -g RT -z reference/SanyaOcu.p_ctg.fa -y restriction_sites/SanyaOcu.p_ctg_DpnII.txt -p restriction_sites/SanyaOcu.p_ctg.chrom.sizes -D /ME4012_Vol0002/Ahome_Dir/hechuanmeng/SY_genome/SY_genome/sanya_genome/raw_data/3d-DNA/juicer/ -s DpnII
The following errors are reported:
Picked up _JAVA_OPTIONS: -Xmx1024m -Xms1024m
Exception in thread "main" java.lang.RuntimeException: Unknown command: statistics
	at juicebox.tools.HiCTools.main(HiCTools.java:98)
Picked up _JAVA_OPTIONS: -Xmx1024m -Xms1024m
Exception in thread "main" java.lang.RuntimeException: Unknown command: statistics
	at juicebox.tools.HiCTools.main(HiCTools.java:98)
Picked up _JAVA_OPTIONS: -Xmx150000m -Xms150000m
/ME4012_Vol0002/Ahome_Dir/hechuanmeng/SY_genome/SY_genome/sanya_genome/raw_data/3d-DNA/aligned/merged1.txt does not exist or does not contain any reads.
Could you tell me how to solve this problem?Thanks!

**Comment by moshe-olshansky** [comment]
Hi there,
Could you ask this question via the 3D Genomics newsgroup?
When you do so, please list the structure of your 
/ME4012_Vol0002/Ahome_Dir/hechuanmeng/SY_genome/SY_genome/sanya_genome/raw_data/3d-DNA/juicer
and
/ME4012_Vol0002/Ahome_Dir/hechuanmeng/SY_genome/SY_genome/sanya_genome/raw_data/3d-DNA/juicer/scripts
folders.

**Comment by 1580542426** [comment]
Thank you. The problem has been solved, but there are new problems

**Comment by 1580542426** [comment]
[fsync] Input/output error
***! Alignment of /ME4012_Vol0002/Ahome_Dir/hechuanmeng/SY_genome/SY_genome/sanya_genome/raw_data/3d-DNA/splits/SY_R1.fastq.gz /ME4012_Vol0002/Ahome_Dir/hechuanmeng/SY_genome/SY_genome/sanya_genome/raw_data/3d-DNA/splits/SY_R2.fastq.gz failed.

**Comment by moshe-olshansky** [comment]
I think that before that statement the aligner (bwa) should have issued its own statements. What did it say?

**Comment by 1580542426** [comment]
> I think that before that statement the aligner (bwa) should have issued its own statements. What did it say?

It doesn't say anything.I would like to ask whether the reference genome file required for HIC auxiliary assembly is the contigs file assembled by HIFI or the reference genome file attached to chromosomes by others.Thanks!

**Comment by sa501428** [comment]
If you're working with genome assembly, you should post this question to the forum: https://groups.google.com/g/3d-genomics
Also see: https://www.dnazoo.org/methods

**Comment by sa501428** [comment]
@1580542426 please stop copy-pasting your question to other unrelated Github issues - these are intended for tracking bugs. Questions about how to run Juicer or 3D-DNA should be asked on the forum (https://groups.google.com/g/3d-genomics) and will get answered there. Thanks!
