### ISSUE TITLE
Path issue for CPU script execution

### ISSUE THREAD

**Issue by photocyte** [theaidenlab/juicer#30]
Hi there,

It seems like there is a bit of a path error for script execution with the "CPU" pipeline.  For example,

> JUICER_INSTALL_DIR=/lab/solexa_weng/testtube/juicer
> SCRIPT_DIR=/lab/solexa_weng/testtube/juicer/CPU/common/
> JUICER_WORK_DIR=(absolute path to directory in current directory, fastq files properly setup there)
> ${JUICER_INSTALL_DIR}/CPU/juicer.sh -D $SCRIPT_DIR -g MyGenome -t 16 -z ../../MyGenome.fasta -p chrom_sizes.txt -y MyGenome.fasta_MboI.txt -d $JUICER_WORK_DIR 1>juicer.stdout.log 2>juicer.stderr.log

Runs for a bit, giving a non-exiting error:

> /lab/solexa_weng/testtube/juicer/CPU/juicer.sh: line 363: /lab/solexa_weng/testtube/juicer/CPU/common//scripts/common/countligations.sh: No such file or directory

and the exiting error:

> awk: fatal: can't open source file /lab/solexa_weng/testtube/juicer/CPU/common//scripts/common/chimeric_blacklist.awk' for reading (No such file or directory)

If we look at where the countligations.sh and chimeric_blacklist.awk files are:

> tfallon@tak4 /lab/solexa_weng/Seq_data/Projects/Tim_Fallon/ppyralis_genome/Genome_project_reference_assemblies/version2/analyses/juicer$ find /lab/solexa_weng/testtube/juicer/ -name countligations.sh
> /lab/solexa_weng/testtube/juicer/CPU/common/countligations.sh
> /lab/solexa_weng/testtube/juicer/SLURM/scripts/countligations.sh
> /lab/solexa_weng/testtube/juicer/AWS/scripts/countligations.sh
> /lab/solexa_weng/testtube/juicer/UGER/scripts/countligations.sh
> /lab/solexa_weng/testtube/juicer/LSF/scripts/countligations.sh

> tfallon@tak4 /lab/solexa_weng/Seq_data/Projects/Tim_Fallon/ppyralis_genome/Genome_project_reference_assemblies/version2/analyses/juicer$ find /lab/solexa_weng/testtube/juicer/ -name chimeric_blacklist.awk
> /lab/solexa_weng/testtube/juicer/CPU/common/chimeric_blacklist.awk
> /lab/solexa_weng/testtube/juicer/SLURM/scripts/chimeric_blacklist.awk
> /lab/solexa_weng/testtube/juicer/AWS/scripts/chimeric_blacklist.awk
> /lab/solexa_weng/testtube/juicer/UGER/scripts/chimeric_blacklist.awk
> /lab/solexa_weng/testtube/juicer/LSF/scripts/chimeric_blacklist.awk
> 

It looks like the issue may be that the juicer.sh script expects "/scripts/common/" as a hardcoded prefix, however the CPU scripts don't follow this convention.  Do you agree?  Or am I executing the juicer pipeline wrong

**Comment by theaidenlab** [comment]
Thanks - someone else noticed this too and made a pull request and I wrote there as well.  See https://github.com/theaidenlab/juicer/pull/26

We're keeping this structure for now and you should soft-link, see https://github.com/theaidenlab/juicer/wiki/Installation#quick-start
