### ISSUE TITLE
how to get sparse matrix for all chromosomes using juicer dump

### ISSUE THREAD

**Issue by jiangshan529** [theaidenlab/juicer#303]
Hi, It seems that Juicer dump can only get sparse matrix for a certain chromosome at one time. Is there a way to get matrix from all chromosomes? Thanks!

**Comment by sa501428** [comment]
I would check out straw; it has some methods that can get a dense matrix (e.g. as a numpy matrix) and is the preferred tool for extracting data from hic files: https://github.com/aidenlab/straw
