### ISSUE TITLE
Why does not run with res: 40000 to produce results

### ISSUE THREAD

**Issue by songxh1996** [theaidenlab/juicer#305]
I encountered the following error, please help me, thank you

java -jar $juicer_tool hiccups --cpu --threads 40 --ignore-sparsity -m 1024 -k KR -p 4,2 -r 25000,40000 -t 0.02,1.5,1.75,2 ${path}/juicer/buffalo_clean.allValidPairs.hic ${path}/loop2

WARN [2023-02-11T21:15:08,162]  [Globals.java:138] [main]  Development mode is enabled
Reading file: /home/songxh/cres/H/zm/longmiss/juicer/buffalo_clean.allValidPairs.hic
Resolution 40000 not available.
Discarding invalid configuration: Config res: 25000 peak: 4 window: 3 fdr: 10% radius: 50000
No valid configurations specified, using default settings
WARNING - You are using the CPU version of HiCCUPS.
The GPU version of HiCCUPS is the official version and has been tested extensively.
The CPU version only searches for loops within 8MB (by default) of the diagonal and is still experimental.
Using 40 CPU thread(s)
Warning Hi-C map is too sparse to find many loops via HiCCUPS.
Default settings for 5kb, 10kb, and 25kb being used
Running HiCCUPS for resolution 5000
4% 
9% ...

**Comment by sa501428** [comment]
Hi, please use the forum for general questions. This has been answered here: https://groups.google.com/g/3d-genomics/c/h5WG8JuKajM/m/2XVARYoqDAAJ
