### ISSUE TITLE
positive or negative signs of eigenvector

### ISSUE THREAD

**Issue by mengwill** [theaidenlab/juicer#315]
**Are you sure this is an issue?**
Github Issues is reserved for situations that require changes to the codebase. Questions, discussions, etc. should be posted to the forum: aidenlab.org/forum.html
When we use the juicer eigenvector function, we found the signs of the vectors are opposite in 2 out of 8 samples. These are hiC datasets. The tracks illustrate the eigenvectors of chromosome 22.

![image](https://github.com/aidenlab/juicer/assets/24279072/85e4d7e1-97e1-4628-a519-d783a1122837)

**Comment by sa501428** [comment]
As with any correlation matrix the sign of the eigenvector is arbitrary. So you can always multiply it by -1 and flip the sign. To know what the correct sign is for the original eigenvector code, you need additional information beyond Hi-C data (active genes, methylation, etc.) and you flip the sign to correlate appropriately. 

Our newer code, POSSUMM, will correlate the vectors with housekeeping genes.
