### ISSUE TITLE
Can I generate an asymmetric .hic file for an asymmetric matrix, and to illustrate the unsymmetric matrix by JuiceBox?

### ISSUE THREAD

**Issue by luoxun-xl** [theaidenlab/juicer#319]
Hi, RNA-DNA interaction pairs data could produce an asymmetric contact matrix. So could I generate an unsymmetric `.hic` file for an asymmetric matrix, and visualize the asymmetric matrix by JuiceBox?

**Comment by sa501428** [comment]
Yes, you'd have to make it an inter-chromosomal region. For example, chr1 would become instead be 2 pseudo chromosomes, dna_chr1 and rna_chr1. You can then view this in juicebox under the inter-chromosomal contacts. If you want to load 1d tracks, they would have to be similarly named (dna_chr1, rna_chr1, etc).

**Comment by luoxun-xl** [comment]
Hi, I tried what you said, and it did work.

However, it is a little bit of a flaw in that there are two-part images like the following. Is there any way to fix this?

![image](https://github.com/aidenlab/juicer/assets/62649650/efd54c3c-0068-446f-a6e4-858dfb257a65)

**Comment by sa501428** [comment]
Can you clarify what the issue is? The all-by-all map is usually just for navigation. Once you click on a specific inter-chromosomal region, you should be able to explore it without issue?

If the goal is to specifically plot the all-by-all map, you may want to use straw instead.
