### ISSUE TITLE
juicebox format to fasta: coordinates conversion error

### ISSUE THREAD

**Issue by brysonab** [theaidenlab/juicer#336]
Hi Juicer Team!

I am working with a large plant genome, around 3Gbp. I am having an issue converting the assembly from the reviewed version in Juicebox to fasta format. 

The .agp file seems to be correct: (first 3 lines)
ctg00000001.1   1       2037903 1       W       contig_4076_pilon       1       2037903 +
ctg00000002.1   1       144558  1       W       contig_11429_pilon      1       144558  +
ctg00000003.1   1       11901176        1       W       contig_4092_pilon       1       11901176        +

Here is my command:
juicer post -o out_JBAT_final pilon_out.review.assembly out_JBAT.liftover.agp draft_contigs.fasta

And here is the error:
[E::assembly_to_agp] coordinates conversion error contig_16500_pilon 0

I am wondering if it may have something to do with the scale. Because it is large, the scale should be 2.0 and I set it in Juicebox. 
Any thoughts would be greatly appreciated!
-Abby

**Comment by sa501428** [comment]
Hi! This would actually be more of a 3D-DNA question / should be posted to the forum: https://groups.google.com/g/3d-genomics
