### ISSUE TITLE
generate_site_positions.py fails when location is provided

### ISSUE THREAD

**Issue by lachlansimpson** [theaidenlab/juicer#41]
Slight logic error in the if/else loops at the top.

If genome is one of the listed genomes, AND the location is provided, run still fails because /seq/reference isn't universal.

You need to add an

`elif len(sys.argv)==3` 

(etc) at line 24 *or* check if the len(sys.argv)==4 before and use filename=<location>  instead.

**Comment by lachlansimpson** [comment]
Actually, I think this is the easiest way to do it?

```
genome=sys.argv[2]
if len(sys.argv) == 4: 
  filename=sys.argv[3] 
elif genome == 'hg19': 
  filename='/seq/references/Homo_sapiens_assembly19.fasta' 
elif genome == 'mm9': 
  filename='/seq/references/Mus_musculus_assembly9.fasta' 
elif genome == 'mm10': 
  filename='/seq/references/Mus_musculus_assembly10.fasta' 
elif genome == 'hg18': 
  filename='/seq/references/Homo_sapiens_assembly18.fasta' 
else: 
  print 'Usage: %s <restriction enzyme> <genome> [location]' % (sys.argv[0]) 
  print '<genome> not found and [location] not defined' 
  sys.exit(1) 
```

**Comment by lachlansimpson** [comment]
Oh. I see that this is fixed in master. My bad. Sorry.

**Comment by amv33576** [comment]
I keep getting this error message:
$ python ./generate_site_positions.py 'DpnII' 'hg19'
  File "./generate_site_positions.py", line 9
    print 'Usage: %s <restriction enzyme> <genome> [location]' % (sys.argv[0])
                                                             ^
SyntaxError: invalid syntax

I tried by adding the location in the command line (python generate_site_positions.py DpnII hg19 ~/test/references/Homo_sapiens_assembly19.fasta  --> got same error

Then, I changed the paths in the file generate_site_positions.py,  I changed the path from  
filename='/seq/references/Homo_sapiens_assembly19.fasta'   to
filename='~/test/references/Homo_sapiens_assembly19.fasta'  and it did not work.

Could you please help me to figure out what is wrong?

Thanks,

Anyi
