### ISSUE TITLE
How can I to  call TAD/compartment using juicer_tools ?

### ISSUE THREAD

**Issue by werhoog** [theaidenlab/juicer#52]
Thanks for your good software. But  I  didn't find  a clear way to call TAD or compartment.Can juicer_tools run to call TAD or compartment (by using Arrowhead,HiCCUPS etc?)

Many Thanks!

**Comment by sa501428** [comment]
Yes, Arrowhead can annotate contact domains. A/B compartment calls are contained within the hic files (generated at build time by pre; can also be calculated from eigenvector).
See
https://github.com/theaidenlab/juicer/wiki/Arrowhead
https://github.com/theaidenlab/juicer/wiki/Eigenvector

These commands use the juicer_tools.jar file:
https://github.com/theaidenlab/juicer/wiki/Download

Also, for general questions we suggest using our public forum:
http://aidenlab.org/forum.html

The github issues should be used for reporting bugs.

Best,
- Muhammad S Shamim
