### ISSUE TITLE
Reference file availability on AWS mirror

### ISSUE THREAD

**Issue by vreuter** [theaidenlab/juicer#56]
Hello, I'm downloading reference files for use with Juicer. hg19 works fine (`Homo_sapiens_assembly19.*` at `https://s3.amazonaws.com/juicerawsmirror/opt/juicer/references`), but I can't access mm9. I tried `Mus_musculus_assembly9_norandom.fasta` as in the "Installation" wiki, but that does not work; it fails with a 403 Forbidden response. I tried some variants on the name, but none of those was a hit. I can generated the necessary files if needed, but are they available for mm9 on AWS or elsewhere? Thanks!

**Comment by nchernia** [comment]
Looks like they got deleted at some point.  I've restored them.  Try:

http://juicerawsmirror.s3.amazonaws.com/opt/juicer/references/Mus_musculus_assembly9_norandom.fasta
http://juicerawsmirror.s3.amazonaws.com/opt/juicer/references/Mus_musculus_assembly9_norandom.fasta.amb
http://juicerawsmirror.s3.amazonaws.com/opt/juicer/references/Mus_musculus_assembly9_norandom.fasta.ann
http://juicerawsmirror.s3.amazonaws.com/opt/juicer/references/Mus_musculus_assembly9_norandom.fasta.bwt
http://juicerawsmirror.s3.amazonaws.com/opt/juicer/references/Mus_musculus_assembly9_norandom.fasta.sa
http://juicerawsmirror.s3.amazonaws.com/opt/juicer/references/Mus_musculus_assembly9_norandom.fasta.pac

**Comment by vreuter** [comment]
Yep, I can fetch them now -- thank you!
