### ISSUE TITLE
AWS tutorial

### ISSUE THREAD

**Issue by DoaneAS** [theaidenlab/juicer#6]
Hi,
I cannot seem to find an AMI corresponding to ami-458fc22f.  Was the tutorial moved?  Is it still available?
thanks

**Comment by theaidenlab** [comment]
It's still available.
<img width="1284" alt="screen shot 2016-10-12 at 5 56 10 pm" src="https://cloud.githubusercontent.com/assets/10360916/19330650/52a49708-90a5-11e6-972c-b582e159fea2.png">
Did you press enter after searching?

**Comment by DoaneAS** [comment]
Hi,
It turns out I was on US West AWS.  Changing to US  East fixed the problem. thanks

**Comment by theaidenlab** [comment]
Ah, our apologies - we will look into this. Thanks for letting us know!
