### ISSUE TITLE
juicer pre error for human 

### ISSUE THREAD

**Issue by min1992** [theaidenlab/juicer#63]
hi,
I am using pre to produce .hic file and the command line is:

`java -jar juicer_tools.1.7.6_jcuda.0.8.jar pre -r 40000 -q 30 -f ../01.data/hg19_MobI.txt ../01.data/test3.txt.gz ./M3-736.hic hg19`

while I met this problem:
Start preprocess
Writing header
Writing body
......Error: the chromosome combination 14_15 appears in multiple blocks

Do you know why the error happen? Look forward for your reply. Thank you so much.
min

**Comment by sa501428** [comment]
Hi,

Please use github issues to report bugs only, not for questions about juicer. For help with juicer, please use our forum: aidenlab.org/forum.html

Note that this question has been answered a few times on the forum:
http://aidenlab.org/forum.html?place=msg%2F3d-genomics%2FbPAm69WEXVg%2F9_o_RcdrBAAJ
http://aidenlab.org/forum.html?place=msg%2F3d-genomics%2F2w1OGHo5XdM%2FcIiHCuP_AQAJ
http://aidenlab.org/forum.html?place=msg%2F3d-genomics%2FrbTV7ssDizc%2Fcp-9ftILBwAJ
http://aidenlab.org/forum.html?place=msg%2F3d-genomics%2FxHIlhRzC_RE%2FLZwNoaw_BQAJ

**Comment by min1992** [comment]
Ok, thanks.

min

**Comment by frediee** [comment]
Hi, juicing has always been a routine from onset living with mama. Now that I'm living alone, I'm going back to my old habits.

This has made me hit online in search of a good juicer.  Although,i don't have much money still want an efficient unit that guarantees result. 

As i continue to search, i stumble upon https://www.consumerhome.org/best-juicer-under-100-reviews/ that features some top rated products at the most lowest cost.....

Few other sites i checked also have units of great value but seems this resource has some cheap units, i decided to bring it front for other to help me analyze and suggestions....

Like said, i am a novice in juicer, if there is any support or idea to know which one is great for a bachelor, that'll made it easy for me to narrow my search...

**Comment by frediee** [comment]
Hi, juicing has always been a routine from onset living with mama. Now that I'm living alone, I'm going back to my old habits.

This has made me hit online in search of a good juicer.  Although,i don't have much money still want an efficient unit that guarantees result. 

As i continue to search, i stumble upon [https://consumerhome.org/best-juicer-under-100-reviews/] that features some top rated products at the most lowest cost.....

Few other sites i checked also have units of great value but seems this resource has some cheap units, i decided to bring it front for other to help me analyze and suggestions....


Like said, i am a novice in juicer, if there is any support or idea to know which one is great for a bachelor, that'll made it easy for me to narrow my search...
