### ISSUE TITLE
 Chimeric Ambiguous: 172,284,184 (100.00%)

### ISSUE THREAD

**Issue by MatStz** [theaidenlab/juicer#66]
Good morning,

I don't manage to get any relevant interaction because all reads are considered as amgiguous... Do you have any idea where can the problem comes?

I have checked i didn't mistake with reference genome and  restriction enzyme. My fastq files names finish with _R1.fastq and  _R2.fastq... I have no idea what I messed up. Any help?

Thank you!

Mathias

**Comment by sa501428** [comment]
Please post this question to our forum aidenlab.org/forum.html
See issue #64

**Comment by MatStz** [comment]
OK. Sorry for that
