### ISSUE TITLE
Running HiCCUPS on Cluster

### ISSUE THREAD

**Issue by jlpulice** [theaidenlab/juicer#67]
Hi,

In the documentation, you have a running configuration for HiCCUPS as a command line tool (https://github.com/theaidenlab/juicer/wiki/HiCCUPS) with listed parameter configuration (hiccups [-m matrixSize] [-c chromosome(s)] [-r resolution(s)] <HiC file> <outputDirectory>). 

I would like to run this on a cluster and have cloned the juicer folder, however this just has the juicer_hiccups.sh script which has a very different usage documentation and parameters (Usage: ${0} [-h] -j <juicer_tools_file_path> -i <hic_file_path> -m <bed_file_dir> -g <genome ID>). I have also pulled the Juicebox git and that does not seem to have the command line tool delineated in the HiCCUPS page and there does not appear to be any specific instructions as to how to install and run HiCCUPS. I am running this on a UGER cluster but that has not impacted the ability to run other scripts so far.

Any guidance you can provide would be appreciated.

Thank you!
John

**Comment by danxunLi** [comment]
Hi there,

How was this resolved? I have the same question. Are we to use juicer_hiccups.sh?

Thanks

**Comment by nchernia** [comment]
You can run hiccups using the juicer_tools jar. The juicer_hiccups.sh script is just a helper script for running the jar.
