### ISSUE TITLE
about the "NaN" in the eigenvector

### ISSUE THREAD

**Issue by RuiqinZheng** [theaidenlab/juicer#68]
Hi!
1.
When I use the "java -jar juicer.jar eigenvector VC" ,I got a list of numbers,but why the NaN are inclued in them?
example:
-0.029397563142951257
-0.02960274258599327
-0.06207008998475912
-0.043139410358771786
-0.028268340237111864
-0.04786199875472475
-0.04584968981684931
-0.059708745048858515
-0.06279340484193087
-0.0650027811219531
NaN
NaN
-0.06147038581422599
-0.05674536469321616
-0.0621719639869912
-0.05416975514265792

2.
I wanner know should I remove the  heterochromatin when I caculate the eigenvector in plant?

wish to reply soon!
Thanks!

**Comment by sa501428** [comment]
Hi!
Please post this question to our forum, as this is not a bug and would best be discussed/answered there: aidenlab.org/forum.html  See #64 
Best,
-MSS
