### ISSUE TITLE
generate_site_positions.py how to use for non model organism

### ISSUE THREAD

**Issue by mictadlo** [theaidenlab/juicer#70]
Hi,
It appears that `generate_site_positions.py` only accept human as a reference. Can I use anyhow `generate_site_positions.py` for a nonmodel organism?

Thank you in advance.

Michal

**Comment by weiszd** [comment]
Hi,
The generate_site_positions.py can be used for any organism. I guess the confusion was that it has some default settings for some standard human references when its called with only 2 parameters.  When the generate_site_positions.py is called with 3 parameters the 3rd one is the location of the reference fasta file of any genome. The 2nd parameter (arbitrary name of the genome ) will be used to name the output file.

**Comment by sa501428** [comment]
Please see Issue #64 
Github Issues is for bugs - please post questions to our forum.
Thanks!
