### ISSUE TITLE
Dump command gives an empty file for my .hic data

### ISSUE THREAD

**Issue by tarak77** [theaidenlab/juicer#72]
Hi,

My .hic file produced from a single cell data is:
[nxt-67.allValidPairs.hic.zip](https://github.com/theaidenlab/juicer/files/2338130/nxt-67.allValidPairs.hic.zip)
I am able to view it using Juicebox. 

When trying to use the dump tool for extracting intrachromosomal matrices, I get an empty txt file without any error. I use the following command:
**java -jar juicer_tools.1.7.6_jcuda.0.8.jar dump  observed KR ./NXT-67/nxt-67.allValidPairs.hic 1 1 BP 250000 NXT-67.chr1.250kb.hicpro.txt**

Any help would be great!

P.S. Similar issue with the following .hic file:
[cdx1-25.allValidPairs.hic.zip](https://github.com/theaidenlab/juicer/files/2338139/cdx1-25.allValidPairs.hic.zip)

**Comment by sa501428** [comment]
Hello!
Please post this question to our forum [aidenlab.org/forum.html](http://aidenlab.org/forum.html). See #64 
That way, the forum can become a useful centralized resource :)
