### ISSUE TITLE
Using "Dump" to create a dense matrix does not output the expected number of rows

### ISSUE THREAD

**Issue by HelenLong1** [theaidenlab/juicer#73]
I believe there is a bug in dump when extracting dense matrices. The matrices I extract are always several rows fewer than expected given the chromosome size and bin size. 

The number of rows missing  seems to vary between chromosome and dataset. I have attached an example of the number of rows in two of my datasets extracted at bin sizes 10kb and 50kb compared to the expected number. Some seem to have as many as 20 rows missing. 

[Juicer_dump_missing_rows.txt](https://github.com/theaidenlab/juicer/files/2360671/Juicer_dump_missing_rows.txt)

Thank you,

Helen

**Comment by nchernia** [comment]
Moved this over to Juicebox since that's where the codebase is for dump.
