### ISSUE TITLE
juicer_tools script memory

### ISSUE THREAD

**Issue by sa501428** [theaidenlab/juicer#77]
juicer_tools and juicer_tools48g and similar files hardcode the JVM memory (Xmx), which does not adjust when larger memory amounts are used

**Comment by devonorourke** [comment]
Wondering what exactly we should be modifying the `juicer_tools48g` script to read when we need to modify for increased JVM memory?

Say I have a node with 450 Gb of RAM?

Something like this, for instance? I've altered three lines where it says `##myedit`...

```
HIC`

    dependhic="afterok:$jid"

    jid=`sbatch <<- HIC30 | egrep -o -e "\b[0-9]+$"
	#!/bin/bash -l
	#SBATCH -p $long_queue
	#SBATCH -o $debugdir/hic30-%j.out
	#SBATCH -e $debugdir/hic30-%j.err
	#SBATCH -t $long_queue_time
	#SBATCH -c 24	##myedit
	#SBATCH --ntasks=1
	#SBATCH --mem 450G
	##myedit SBATCH --mem-per-cpu=32G
	#SBATCH -J "${groupname}_hic30"
	#SBATCH -d ${dependstats}
	${load_java}
	export IBM_JAVA_OPTIONS="-Xmx400g -Xgcthreads24"    ##myedit
	date
        if [ -f "${errorfile}" ]
        then 
            echo "***! Found errorfile. Exiting." 
            exit 1 
        fi 
        if [ "$nofrag" -eq 1 ]
        then 
	    ${juiceDir}/scripts/juicer_tools48g pre -s $outputdir/inter_30.txt -g $outputdir/inter_30_hists.m -q 30 $outputdir/merged_nodups.txt $outputdir/inter_30.hic $genomePath
	else
	    ${juiceDir}/scripts/juicer_tools48g pre -f $site_file -s $outputdir/inter_30.txt -g $outputdir/inter_30_hists.m -q 30 $outputdir/merged_nodups.txt $outputdir/inter_30.hic $genomePath
	fi
	date
HIC30`
```

Thanks

**Comment by sa501428** [comment]
Hey @devonorourke ,
In addition to those lines, you would need to edit ${juiceDir}/scripts/juicer_tools48g
Specifically the -Xmx#g in that java call within that file.

**Comment by devonorourke** [comment]
Hi @sa501428 ,

Hopefully the code I embedded in the initial message represented a potentially useful `-Xmx` call?

```
export IBM_JAVA_OPTIONS="-Xmx400g -Xgcthreads24"    ##myedit
```

If I specify a node with 450G RAM and 24 threads, it's my understanding that providing the above command would be sufficient.

Thanks for your response

**Comment by sa501428** [comment]
That change does need to be made, but the following line in juicer_tools48g also needs to be updated

`java -Djava.awt.headless=true -Djava.library.path=dirname $0/lib64 -Xms49152m -Xmx49152m -jar dirname $0/juicer_tools.jar $*
`

**Comment by devonorourke** [comment]
Thanks again @sa501428 ,
I've made both changes now. 
Can you help me understand one additional thing: even if the program is stalling on the statistics portion of the `juicer.sh` script, would I still be able to use the `.hic` file for downstream work in the 3d-dna pipeline? Or is there additional checks that must be performed before passing that file into the next part of the workflow that the _stats_ part of juicer is crashing on?
Cheers

**Comment by devonorourke** [comment]
Quick follow up @sa501428 - the updates to those two scripts, as noted in this thread, resolved all issues. The script using your test dataset completed successfully with those changes.

**Comment by nchernia** [comment]
@sa501428 was this ever pushed to master?

**Comment by sa501428** [comment]
i don't think so

**Comment by nchernia** [comment]
@devonorourke @sa501428 shouldn't it be sufficient to export the Java options? In which case we wouldn't need to also have it in the juicer_tools script (ie can we eliminate the -Xmx flag from juicer_tools?) Or perhaps we should make this an optional argument to the juicer_tools script instead of having 5 different versions floating around?

**Comment by nchernia** [comment]
@sa501428 thoughts on my last comment? would like to fix this in next version coming out in the next few days.

**Comment by sa501428** [comment]
agreed with passing in an argument to juicer_tools instead of having several versions with a different hardcoded memory value

**Comment by nchernia** [comment]
Recommendation is to explicitly export the memory options before calling the script.

`export _JAVA_OPTIONS="-Xmx49152m -Xms49152m" `
