### ISSUE TITLE
what is motif file?

### ISSUE THREAD

**Issue by shenweima** [theaidenlab/juicer#81]
the software tell me that 
Motifs read from /data2/masw_data/genome_assembly/juicer/references/motif
However, I don't have motif file.
I only have restriction site file in ./restriction_sites/TGACv2.draft.fa_HindIII.txt
`${juiceDir}/scripts/common/juicer_postprocessing.sh -j ${juiceDir}/scripts/common/juicer_tools -i ${outputdir}/inter_30.hic -m ${juiceDir}/references/motif -g ${genomeID}
`
So how to get motif file for my genome?

**Comment by sa501428** [comment]
Hi! Can you please post this question to our forum, and we will answer it there? Thanks! #64 
[aidenlab.org/forum.html](http://aidenlab.org/forum.html)
