### ISSUE TITLE
Feature Request: Multiple Ligation Sites Option 

### ISSUE THREAD

**Issue by mzhibo** [theaidenlab/juicer#84]
I recently also encountered some data sets that used restriction enzymes recognizing multiple sites (such as G^ANTC) or using multiple enzymes. As some commercial kits are using this multiple restriction enzyme sites strategy, I guess more and more people might face similar issue sooner or later. Would you consider adding a new feature to the juicer pipeline to take multiple ligation sites either through the -b flag or edit the $ligation variable in the juicer.sh?  I think this would be a popular feature that the community will like.

**Comment by nchernia** [comment]
Thanks, this is now supported in Juicer (SLURM). Using the -b option, you could write:

`-b '(GATCGATC|AAGCTAGCTT)'`

For MboI+HindIII for example.
