### ISSUE TITLE
juicer on aws align/merge jobs pending

### ISSUE THREAD

**Issue by aboyher** [theaidenlab/juicer#90]
I'm not sure what the issue is or what to report to give context. I am trying to run juicer on an AWS m4.2xlarge, so 32 Gb RAM, and 500Gb storage (I think storage size might be an issue). My fastq files are gzipped at28 and 31 Gb. Every time I run juicer, a couple of the align jobs finish but the merge jobs are always left pending.

**Comment by nchernia** [comment]
Please post on the forum at aidenlab.org/forum.html and someone will respond soon.
