### ISSUE TITLE
juicer.sh Error creating main window null    Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by pkubgmlixs** [theaidenlab/juicer#93]
When I run the juicer.sh script to create hic contact  map from raw fastq files, I always get errors below.
 I log in remote server from windows OS using Xshell6, is this related to this kind of error? And does anyone konw how to solove this error? 

 my command is   "./scripts/juicer.sh   -g hg19 -d  /rd1/user/lixs/tmp/juicer_test/work/HIC003  -p  /rd1/user/lixs/tmp/juicer_test/references/hg19.sizes   -y  /rd1/user/lixs/tmp/juicer_test/restriction_sites/hg19_MboI.txt   -z  /rd1/user/lixs/tmp/juicer_test/references/hg19.fa  -D  /rd1/user/lixs/tmp/juicer_test   -s MboI    1>HIC003_juicer.log 2>HIC003_juicer.err  -t  40  "

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 2348578 sequences (234857800 bp)...
[M::mem_process_seqs] Processed 2348578 reads in 1254.619 CPU sec, 31.785 real sec
[main] Version: 0.7.13-r1126
[main] CMD: bwa mem -t 40 /rd1/user/lixs/tmp/juicer_test/references/hg19.fa /rd1/user/lixs/tmp/juicer_test/work/HIC003/splits/HIC003_S2_L001_R1_001.fastq.gz
[main] Real time: 49.143 sec; CPU: 1271.616 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 2348578 sequences (234857800 bp)...
[M::mem_process_seqs] Processed 2348578 reads in 1240.513 CPU sec, 31.449 real sec
[main] Version: 0.7.13-r1126
[main] CMD: bwa mem -t 40 /rd1/user/lixs/tmp/juicer_test/references/hg19.fa /rd1/user/lixs/tmp/juicer_test/work/HIC003/splits/HIC003_S2_L001_R2_001.fastq.gz
[main] Real time: 49.032 sec; CPU: 1257.425 sec
Picked up _JAVA_OPTIONS: -Xmx16384m
Picked up _JAVA_OPTIONS: -Xmx16384m
Default User Directory: /home/lixs
HiC Directory: /home/lixs/juicebox
**Error creating main window null
Exception in thread "main" java.lang.NullPointerException
        at juicebox.MainWindow.main(MainWindow.java:116)**
Picked up _JAVA_OPTIONS: -Xmx16384m
Picked up _JAVA_OPTIONS: -Xmx16384m
Default User Directory: /home/lixs
HiC Directory: /home/lixs/juicebox
**Error creating main window null
Exception in thread "main" java.lang.NullPointerException
        at juicebox.MainWindow.main(MainWindow.java:116)**

 By the way, when I run Juicebox_1.9.8.jar script, I got similar error  related to X11  as shown below.

**Error creating main window 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
Exception in thread "main" java.lang.NullPointerException
        at juicebox.MainWindow.main(MainWindow.java:116)**

**Comment by sa501428** [comment]
I believe this should be fixed in the new dev version 1.9.9. Can you let us know if that's the case? https://github.com/aidenlab/Juicer/wiki/Download

**Comment by pkubgmlixs** [comment]
OK. I will try the new version and reply to you! Thank you!




发自网易邮箱大师
On 01/11/2019 23:24, Muhammad Saad Shamim wrote:

I believe this should be fixed in the new dev version 1.9.9. Can you let us know if that's the case? https://github.com/aidenlab/Juicer/wiki/Download
